import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
const cli=new URL("../dist/cli.js",import.meta.url);
function run(args,input=""){const {promise,resolve,reject}=Promise.withResolvers();const child=spawn(process.execPath,[cli.pathname,...args],{cwd:new URL("..",import.meta.url),stdio:["pipe","pipe","pipe"]});let stdout="",stderr="";child.stdout.setEncoding("utf8").on("data",s=>stdout+=s);child.stderr.setEncoding("utf8").on("data",s=>stderr+=s);child.once("error",reject);child.once("close",code=>resolve({code,stdout,stderr}));child.stdin.end(input);return promise}
test("help and version are standalone",async()=>{const help=await run(["--help"]);assert.equal(help.code,0);assert.match(help.stdout,/Usage: agent-docx/);const bad=await run(["--help","x.md"]);assert.equal(bad.code,2);assert.match(bad.stderr,/INVALID_ARGUMENT/)});
test("single JSON is clean and strict UTF-8",async()=>{const result=await run(["--json"],"A short filing.\n");assert.equal(result.code,0);assert.equal(result.stderr,"");assert.equal(JSON.parse(result.stdout).schemaVersion,1)});
test("boundary fixture through committed config",async()=>{const result=await run(["test/fixtures/28-hard-lines.md","--config","test/fixtures/exact-27-lines.json","--json"]);assert.equal(result.code,0,result.stderr);const measurement=JSON.parse(result.stdout);assert.equal(measurement.pageCount,2);assert.equal(measurement.deterministic.equivalentPages,1+24/648)});
test("usage grammar rejects leading-zero counts",async()=>{const result=await run(["--page-limit","01","--json"],"Text");assert.equal(result.code,2);assert.match(result.stderr,/INVALID_ARGUMENT/)});
test("positional batch preserves order and emits JSONL",async()=>{const result=await run(["--batch","test/fixtures/27-hard-lines.md","test/fixtures/28-hard-lines.md"]);assert.equal(result.code,0,result.stderr);const records=result.stdout.trim().split("\n").map(JSON.parse);assert.equal(records.length,2);assert.equal(records[0].source.path,"test/fixtures/27-hard-lines.md");assert.equal(records[1].sequence,2)});
test("explicit missing LibreOffice does not fall back",async()=>{const result=await run(["--renderer","libreoffice","--libreoffice-path","/definitely/missing/soffice","--json"],"Text");assert.equal(result.code,4);assert.match(result.stderr,/LIBREOFFICE_NOT_FOUND/)});
