import { access, mkdtemp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import { PDFDocument } from "pdf-lib";
import { MdPageCountError, type LibreOfficeRendererOptions, type LibreOfficeRendering, type WordRendererOptions, type WordRendering } from "../types.js";
const sha=(b:Uint8Array)=>createHash("sha256").update(b).digest("hex");
type ProcessResult={code:number|null;stdout:string;stderr:string;timedOut:boolean};
async function run(executable:string,args:string[],stdin:string|undefined,timeoutMs:number,env?:NodeJS.ProcessEnv):Promise<ProcessResult>{const child=spawn(executable,args,{shell:false,stdio:["pipe","pipe","pipe"],detached:process.platform!=="win32",env});const chunksOut:Buffer[]=[],chunksErr:Buffer[]=[];let out=0,err=0,timedOut=false;child.stdout.on("data",(b:Buffer)=>{out+=b.length;if(out<=1024*1024)chunksOut.push(b)});child.stderr.on("data",(b:Buffer)=>{err+=b.length;if(err<=1024*1024)chunksErr.push(b)});if(stdin===undefined)child.stdin.end();else child.stdin.end(stdin);const timer=setTimeout(()=>{timedOut=true;if(process.platform!=="win32"&&child.pid)process.kill(-child.pid,"SIGKILL");else child.kill("SIGKILL")},timeoutMs);const {promise,resolve,reject}=Promise.withResolvers<number|null>();child.once("error",reject);child.once("close",resolve);let code:number|null;try{code=await promise}finally{clearTimeout(timer)}return{code,stdout:Buffer.concat(chunksOut).toString("utf8"),stderr:Buffer.concat(chunksErr).toString("utf8"),timedOut}}
async function exists(path:string){try{await access(path,constants.X_OK);return true}catch{return false}}
export async function resolveLibreOffice(explicit?:string):Promise<string>{if(explicit){if(!explicit.startsWith("/")&&process.platform!=="win32")throw new MdPageCountError("INVALID_ARGUMENT","LibreOffice executable path must be absolute");if(await exists(explicit))return explicit;throw new MdPageCountError("LIBREOFFICE_NOT_FOUND",`LibreOffice executable not found: ${explicit}`)}const candidates:string[]=[];if(process.platform==="darwin")candidates.push("/Applications/LibreOffice.app/Contents/MacOS/soffice");if(process.platform==="win32"){for(const base of [process.env.ProgramFiles,process.env["ProgramFiles(x86)"]])if(base)candidates.push(join(base,"LibreOffice","program","soffice.com"))}else for(const dir of (process.env.PATH??"").split(delimiter))for(const name of ["soffice","libreoffice"])candidates.push(join(dir,name));for(const candidate of candidates)if(await exists(candidate))return candidate;throw new MdPageCountError("LIBREOFFICE_NOT_FOUND","LibreOffice Writer executable was not found")}
export async function renderLibreOffice(docx:Uint8Array,requestedFontFamilies:readonly string[],options:LibreOfficeRendererOptions={},timeoutMs=60000):Promise<LibreOfficeRendering>{const executable=await resolveLibreOffice(options.executablePath);const versionResult=await run(executable,["--version"],undefined,10000);if(versionResult.code!==0)throw new MdPageCountError("LIBREOFFICE_RENDER_FAILED","LibreOffice version preflight failed",{stderr:versionResult.stderr});const root=await mkdtemp(join(tmpdir(),"md-page-count-lo-"));const inputDir=join(root,"input"),outputDir=join(root,"output"),profileDir=join(root,"profile");const input=join(inputDir,"render.docx");const start=performance.now();try{await Promise.all([mkdir(inputDir),mkdir(outputDir),mkdir(profileDir)]);await writeFile(input,docx);await writeFile(join(profileDir,"registrymodifications.xcu"),"<?xml version=\"1.0\" encoding=\"UTF-8\"?><oor:items xmlns:oor=\"http://openoffice.org/2001/registry\"></oor:items>");const args=[`-env:UserInstallation=${pathToFileURL(profileDir).href}`,"--headless","--nologo","--nodefault","--norestore","--infilter=Office Open XML Text","--convert-to","pdf:writer_pdf_Export","--outdir",outputDir,input];const rendered=await run(executable,args,undefined,timeoutMs,{...process.env,LC_ALL:"C",LANG:"C",TZ:"UTC"});if(rendered.timedOut)throw new MdPageCountError("LIBREOFFICE_TIMEOUT",`LibreOffice exceeded ${timeoutMs} ms`);if(rendered.code!==0)throw new MdPageCountError("LIBREOFFICE_RENDER_FAILED","LibreOffice conversion failed",{stderr:rendered.stderr});const pdfPath=join(outputDir,"render.pdf");const info=await stat(pdfPath);if(!info.isFile()||info.isSymbolicLink()||info.size===0)throw new MdPageCountError("LIBREOFFICE_RENDER_FAILED","LibreOffice did not create a regular nonempty PDF");const pdf=await readFile(pdfPath);let loaded:PDFDocument;try{loaded=await PDFDocument.load(pdf,{ignoreEncryption:false,updateMetadata:false,throwOnInvalidObject:true})}catch{throw new MdPageCountError("LIBREOFFICE_RENDER_FAILED","LibreOffice produced an invalid or encrypted PDF")}const pageCount=loaded.getPageCount();if(pageCount<1)throw new MdPageCountError("LIBREOFFICE_RENDER_FAILED","LibreOffice PDF has no pages");const calibrated=Boolean(options.installedFonts?.length);return{pageCount,versionRaw:versionResult.stdout.trim()||versionResult.stderr.trim(),executablePath:executable,platform:process.platform,arch:process.arch,calibratedFontEnvironment:calibrated,requestedFontFamilies,generatedDocxSha256:sha(docx),pdfSha256:sha(pdf),durationMs:performance.now()-start}}finally{await rm(root,{recursive:true,force:true,maxRetries:4,retryDelay:50})}}
async function resolveWordPath(options:WordRendererOptions){if(options.powerShellPath){if(await exists(options.powerShellPath))return options.powerShellPath;throw new MdPageCountError("WORD_NOT_FOUND",`PowerShell not found: ${options.powerShellPath}`)}if(process.platform==="win32"){const root=process.env.SystemRoot??"C:\\Windows";const candidate=join(root,"System32","WindowsPowerShell","v1.0","powershell.exe");if(await exists(candidate))return candidate}if(/microsoft/i.test(await readFile("/proc/sys/kernel/osrelease","utf8").catch(()=>""))){const candidate="/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe";if(await exists(candidate))return candidate}throw new MdPageCountError("WORD_NOT_FOUND","Microsoft Word PowerShell bridge is unavailable")}
export async function renderWord(docx:Uint8Array,requestedFontFamilies:readonly string[],options:WordRendererOptions={},timeoutMs=120000):Promise<WordRendering>{if(docx.byteLength>25*1024*1024)throw new MdPageCountError("WORD_RENDER_FAILED","Generated DOCX exceeds Word adapter limit");const powershell=await resolveWordPath(options);let script=fileURLToPath(new URL("../../assets/word/render.ps1",import.meta.url));if(powershell.startsWith("/mnt/")&&process.platform!=="win32"){if(!await exists("/usr/bin/wslpath"))throw new MdPageCountError("WORD_WSL_BRIDGE_UNAVAILABLE","/usr/bin/wslpath is unavailable");const converted=await run("/usr/bin/wslpath",["-w",script],undefined,5000);if(converted.code!==0)throw new MdPageCountError("WORD_WSL_BRIDGE_UNAVAILABLE","wslpath failed");script=converted.stdout.trim()}const start=performance.now();const response=await run(powershell,["-NoLogo","-NoProfile","-NonInteractive","-File",script],JSON.stringify({ docxBase64: Buffer.from(docx).toString("base64"), requestedFontFamilies }),timeoutMs);if(response.timedOut)throw new MdPageCountError("WORD_TIMEOUT",`Word exceeded ${timeoutMs} ms`);const frames=response.stdout.split(/\r?\n/).filter(Boolean).map(line=>{try{return JSON.parse(line) as unknown}catch{return null}});const result=frames.find(frame=>frame&&typeof frame==="object"&&"kind" in frame&&frame.kind==="result");if(!result||typeof result!=="object"||!("pageCount" in result)||typeof result.pageCount!=="number")throw new MdPageCountError("WORD_RENDER_FAILED","Word adapter did not return a result",{stderr:response.stderr,stdout:response.stdout});const value=result as {pageCount:number;bodyLinesOnLastPage:number;version:string;build:string;activePrinter:string};return{pageCount:value.pageCount,bodyLinesOnLastPage:value.bodyLinesOnLastPage,version:value.version,build:value.build,activePrinter:value.activePrinter,requestedFontFamilies,generatedDocxSha256:sha(docx),durationMs:performance.now()-start,cleanupState:"complete"}}
