import LineBreaker from "linebreak";
import type { Font } from "fontkit";
import type { FlowBlock, InlineRun, NormalizedDocument } from "../markdown.js";
import type { Diagnostic, LayoutProfile, ParagraphDiagnostic, TextStyle } from "../types.js";
import type { LoadedFonts } from "../resolve.js";
export type PaginationOutput={pageCount:number;equivalentPages:number;totalVisualLines:number;lastPage:{visualLines:number;usedTwips:number;usableTwips:number;bodyLineEquivalentsUsed:number;bodyLineCapacity:number}|null;paragraphs:ParagraphDiagnostic[];warnings:Diagnostic[]};
type WrappedLine={used:number;available:number;height:number;text:string;block:FlowBlock;counted:boolean};
type Page={used:number;visual:number;counted:number;lines:WrappedLine[]};
const round=(n:number)=>Math.sign(n)*Math.floor(Math.abs(n)+0.5);
const role=(run:InlineRun)=>run.bold?(run.italic?"boldItalic":"bold"):(run.italic?"italic":"regular") as keyof Pick<LoadedFonts,"regular"|"bold"|"italic"|"boldItalic">;
function width(font:Font,text:string,size:number){const layout=font.layout(text);return round(layout.positions.reduce((sum,p)=>sum+p.xAdvance,0)*size/font.unitsPerEm)}
function candidateWidth(block:FlowBlock,start:number,end:number,fonts:LoadedFonts,style:TextStyle){let cursor=0,total=0;for(const run of block.runs){const next=cursor+run.text.length;const a=Math.max(start,cursor),b=Math.min(end,next);if(b>a)total+=width(fonts[role(run)].font,run.text.slice(a-cursor,b-cursor),style.fontSizeTwips);cursor=next}return total}
function naturalHeight(fonts:LoadedFonts,block:FlowBlock,style:TextStyle,start:number,end:number){let cursor=0,max=0;for(const run of block.runs){const next=cursor+run.text.length;if(Math.min(end,next)>Math.max(start,cursor)){const f=fonts[role(run)].font;max=Math.max(max,round((f.ascent-f.descent+f.lineGap)*style.fontSizeTwips/f.unitsPerEm))}cursor=next}return max||style.fontSizeTwips}
function linePitch(natural:number,style:TextStyle){return style.lineSpacing.rule==="auto"?round(natural*style.lineSpacing.numerator/240):style.lineSpacing.rule==="exact"?style.lineSpacing.twips:Math.max(natural,style.lineSpacing.twips)}
function warnMissingGlyphs(block:FlowBlock,fonts:LoadedFonts,warnings:Diagnostic[]){for(const run of block.runs){const font=fonts[role(run)].font;for(const character of run.text){const codePoint=character.codePointAt(0)!;if(!font.hasGlyphForCodePoint(codePoint)){warnings.push({code:"MISSING_GLYPH",severity:"warning",message:`The selected metric font has no glyph for U+${codePoint.toString(16).toUpperCase().padStart(4,"0")}.`,position:block.position});return}}}}
function wrap(block:FlowBlock,style:TextStyle,available:number,fonts:LoadedFonts,warnings:Diagnostic[]): WrappedLine[] { warnMissingGlyphs(block, fonts, warnings); ;const text=block.runs.map(r=>r.text).join("");const lines:WrappedLine[]=[];let segmentStart=0;const mandatory=[...text.matchAll(/\n/g)].map(m=>(m.index??0)+1);mandatory.push(text.length);for(const segmentEndWithBreak of mandatory){const segmentEnd=segmentEndWithBreak<text.length?segmentEndWithBreak-1:segmentEndWithBreak;let start=segmentStart;if(start===segmentEnd){const natural=naturalHeight(fonts,block,style,start,endSafe(start,text.length));lines.push({used:0,available,height:linePitch(natural,style),text:"",block,counted:block.kind!=="blockquote"&&block.kind!=="footnote"})}while(start<segmentEnd){const breaker=new LineBreaker(text.slice(start,segmentEnd));const opportunities:number[]=[];let br;while((br=breaker.nextBreak())!==null)opportunities.push(start+br.position);if(opportunities.at(-1)!==segmentEnd)opportunities.push(segmentEnd);let chosen=start;for(const end of opportunities){const used=candidateWidth(block, start, end, fonts, style);if(used<=available)chosen=end;else break}if(chosen===start){chosen=opportunities[0]??segmentEnd;warnings.push({code:"UNBREAKABLE_OVERFLOW",severity:"warning",message:"An unbreakable token exceeds the available line width.",position:block.position})}const used=candidateWidth(block, start, chosen, fonts, style);const natural=naturalHeight(fonts,block,style,start,chosen);lines.push({used,available,height:linePitch(natural,style),text:text.slice(start,chosen).trimEnd(),block,counted:block.kind!=="blockquote"&&block.kind!=="footnote"});start=chosen;while(text[start]===" ")start++}segmentStart=segmentEndWithBreak}return lines }
const endSafe=(n:number,length:number)=>Math.min(length,n+1);
function styleFor(profile:LayoutProfile,b:FlowBlock){return b.kind==="heading"?profile.headings[String(b.level??1) as "1"]:b.kind==="blockquote"?profile.blockquote:b.kind==="list"?profile.list:b.kind==="footnote"?profile.footnote:profile.body}
export function paginate(doc:NormalizedDocument,profile:LayoutProfile,fonts:LoadedFonts):PaginationOutput{if(doc.blocks.length===0)return{pageCount:0,equivalentPages:0,totalVisualLines:0,lastPage:null,paragraphs:[],warnings:[]};const usableW=profile.page.widthTwips-profile.page.marginsTwips.left-profile.page.marginsTwips.right-profile.page.gutterTwips;const usableH=profile.page.heightTwips-profile.page.marginsTwips.top-profile.page.marginsTwips.bottom;const warnings:Diagnostic[]=[];const pages:Page[]=[];let page:Page={used:0,visual:0,counted:0,lines:[]};const commitPage=()=>{pages.push(page);page={used:0,visual:0,counted:0,lines:[]}};let priorAfter=0;for(const block of doc.blocks){if(block.kind==="pagebreak"){commitPage();priorAfter=0;continue}const style=styleFor(profile,block);const available=usableW-style.leftIndentTwips-style.rightIndentTwips;let wrapped=wrap(block,style,available,fonts,warnings);if(profile.id==="frap-32"&&block.kind==="blockquote"&&wrapped.length>=3){const single={...style,lineSpacing:{rule:"auto",numerator:240,denominator:240} as const};wrapped=wrap(block,single,available,fonts,warnings)}const spacing=Math.max(priorAfter,style.beforeTwips);if(page.used>0&&page.used+spacing>usableH)commitPage();page.used+=page.used>0?spacing:0;const blockHeight=wrapped.reduce((n,l)=>n+l.height,0);if(style.keepLines&&page.used>0&&blockHeight<=usableH&&page.used+blockHeight>usableH)commitPage();for(let i=0;i<wrapped.length;i++){const line=wrapped[i]!;const cap=profile.pagination.maxCountedLinesPerPage;const hitsCap=line.counted&&cap!==null&&page.counted>=cap;const hitsGeometry=page.used+line.height>usableH;if((hitsCap||hitsGeometry)&&page.lines.length>0){const remaining=wrapped.length-i;if(remaining<profile.pagination.widowLines&&i>=profile.pagination.orphanLines){const move=Math.min(profile.pagination.orphanLines,i);const moved=page.lines.splice(-move);for(const m of moved){page.used-=m.height;page.visual--;if(m.counted)page.counted--}commitPage();for(const m of moved){page.lines.push(m);page.used+=m.height;page.visual++;if(m.counted)page.counted++}}else commitPage()}page.lines.push(line);page.used+=line.height;page.visual++;if(line.counted)page.counted++}priorAfter=style.afterTwips}
if(page.lines.length>0||pages.length===0)pages.push(page);const paragraphResults:ParagraphDiagnostic[]=[];let index=0;for(const block of doc.paragraphs){const occurrences: {page:number;line:WrappedLine}[]=[];pages.forEach((p,pi)=>p.lines.forEach(line=>{if(line.block===block)occurrences.push({page:pi+1,line})}));if(occurrences.length){const last=occurrences.at(-1)!;paragraphResults.push({source:"deterministic",index:index++,position:block.position,startPage:occurrences[0]!.page,endPage:last.page,visualLines:occurrences.length,lastLineUsedTwips:last.line.used,lastLineAvailableTwips:last.line.available,lastLineRatio:last.line.available===0?0:last.line.used/last.line.available,preview:block.runs.map(r=>r.text).join("").replace(/\s+/g," ").trim().slice(0,80)})}}
const last=pages.at(-1)!;const bodyNatural=naturalHeight(fonts,{...doc.blocks.find(b=>b.kind!=="pagebreak")!,runs:[{text:"Ag",bold:false,italic:false}]},profile.body,0,2);const bodyPitch=linePitch(bodyNatural,profile.body);return{pageCount:pages.length,equivalentPages:pages.length-1+last.used/usableH,totalVisualLines:pages.reduce((n,p)=>n+p.visual,0),lastPage:{visualLines:last.visual,usedTwips:last.used,usableTwips:usableH,bodyLineEquivalentsUsed:last.used/bodyPitch,bodyLineCapacity:Math.floor(usableH/bodyPitch)},paragraphs:paragraphResults,warnings}}
